### ISSUE TITLE
failed at docker building 

### ISSUE THREAD

**Issue by zhhongzhi** [davidgolub/SimpleQA#1]
Error reported when building the docker，detailed infomation is as follow, it seems that the url is not avaliable now.
Thank you for your reply.
 

hongzhi@hongzhi-Runner:/mydata/wp/SimpleQA$ docker build -t simpleqa .
Sending build context to Docker daemon  42.4 MB
Step 1 : FROM ubuntu:14.04
 ---> 7c09e61e9035
Step 2 : RUN apt-get update
 ---> Using cache
 ---> b65fd1767de7
Step 3 : RUN apt-get install git -y
 ---> Using cache
 ---> ed320257ff4e
Step 4 : RUN apt-get install curl -y
 ---> Using cache
 ---> 63d3d1d00fb8
Step 5 : RUN apt-get install wget -y
 ---> Using cache
 ---> 58e1a803d795
Step 6 : RUN apt-get install python-dev -y
 ---> Using cache
 ---> 3c46882f8df4
Step 7 : RUN apt-get install python-pip -y
 ---> Using cache
 ---> fd3b26d0929b
Step 8 : RUN apt-get -y install python-pip
 ---> Using cache
 ---> 98203337c0d0
Step 9 : RUN pip install --upgrade numpy
 ---> Using cache
 ---> 143cb4a5aae1
Step 10 : RUN pip install cassandra-driver
 ---> Using cache
 ---> 836c5d37bf7a
Step 11 : RUN pip install cqlengine
 ---> Using cache
 ---> a0c3eae3668c
Step 12 : RUN pip install unidecode
 ---> Using cache
 ---> a5ee3761a6bb
Step 13 : RUN pip install elasticsearch
 ---> Using cache
 ---> faf22f6a1920
Step 14 : RUN apt-get install -y pv
 ---> Using cache
 ---> 37e1367c3225
Step 15 : RUN apt-get install -y libpq-dev
 ---> Using cache
 ---> f7e432a336ce
Step 16 : RUN pip install tinys3
 ---> Using cache
 ---> ae18e0806104
Step 17 : RUN pip install boto
 ---> Using cache
 ---> 5f1c6c5d7cef
Step 18 : RUN pip install filechunkio
 ---> Using cache
 ---> d91afa680678
Step 19 : RUN apt-get install -y software-properties-common
 ---> Using cache
 ---> 36abc9ca800e
Step 20 : RUN curl -sk https://raw.githubusercontent.com/davidgolub/WorkSamples/master/torch_install.sh install-deps | bash
 ---> Running in 297fddbdea0e
bash: line 1: 404:: command not found
The command '/bin/sh -c curl -sk https://raw.githubusercontent.com/davidgolub/WorkSamples/master/torch_install.sh install-deps | bash' returned a non-zero code: 127

**Comment by zhhongzhi** [comment]
Assumpting that this command aims at install the torch thus I replaced the command with this one, wondering whether it is proper.
RUN curl -s https://raw.github.com/clementfarabet/torchinstall/master/install-all | bash
however there is another error raised.

Step 17 : RUN pip install boto
 ---> Using cache
 ---> 5f1c6c5d7cef
Step 18 : RUN pip install filechunkio
 ---> Using cache
 ---> d91afa680678
Step 19 : RUN apt-get install -y software-properties-common
 ---> Using cache
 ---> 36abc9ca800e
Step 20 : RUN curl -s https://raw.github.com/clementfarabet/torchinstall/master/install-all | bash  # i add this
 ---> Using cache
 ---> 8676a4cc8710
Step 21 : RUN git clone https://github.com/torch/distro.git ~/torch --recursive
 ---> Using cache
 ---> 831d16c8fd7e
Step 22 : RUN cd ~/torch; ./install.sh
 ---> Running in 09cee4c0716a
Prefix set to /root/torch/install
Installing Lua version: LUAJIT21
./install.sh: line 68: cmake: command not found
The command '/bin/sh -c cd ~/torch; ./install.sh' returned a non-zero code: 1

**Comment by davidgolub** [comment]
Hi zzhongzhi.
Thank you for your comments.

I have updated the repo and README instructions so you can use a pre-built docker image instead of building it from scratch.

Now you should be able to run "docker pull davidgolub/simpleqa" instead of "docker build -t simpleqa ."

The rest of the instructions remain the same.

Thanks and good luck!
David
